### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by lozohcum** [cacois/flask-angular2-starter#3]
When trying to execute
` python manage.py initdb`

it returns error:

> Traceback (most recent call last):
  File "manage.py", line 2, in <module>
    from flask_app.app import app
  File "C:\Users\lozohcum\Documents\Projects\flask-angular2-starter\src\server\flask_app\__init__.py", line 6, in <module>
    from .models import Role, User
  File "C:\Users\lozohcum\Documents\Projects\flask-angular2-starter\src\server\flask_app\models\__init__.py", line 2, in <module>
    from user import User
ImportError: No module named 'user'

**Comment by lozohcum** [comment]
I changed _init_.py to
from .user import User
from .role import Role

but now I'm getting 

>   File "C:\Users\lozohcum\Documents\Projects\flask-angular2-starter\src\server\flask_app\models\user.py", line 2, in <module>
>     from base import Base
> ImportError: No module named 'base'

it's neverending import errors

**Comment by lozohcum** [comment]
I had to change all imports to relative and it seems to work now
so every from xyz import XYZ changed to
from .xyz import XYZ

**Comment by bsamadi** [comment]
Thank you @lozohcum . I managed to run the Python server. When I try "npm run server:dev:hmr", I get the following errors on Ubuntu:

ERROR in ./src/vendor.browser.ts
Module build failed: TypeError: utils.getOptions is not a function
    at Object.Angular2HMRLoader (/home/behzad/PycharmProjects/flask-angular2-starter/src/client/node_modules/@angularclass/hmr-loader/index.js:10:21)
 @ multi vendor

ERROR in ./src/polyfills.browser.ts
Module build failed: TypeError: utils.getOptions is not a function
    at Object.Angular2HMRLoader (/home/behzad/PycharmProjects/flask-angular2-starter/src/client/node_modules/@angularclass/hmr-loader/index.js:10:21)
 @ multi polyfills

ERROR in ./src/main.browser.ts
Module build failed: TypeError: utils.getOptions is not a function
    at Object.Angular2HMRLoader (/home/behzad/PycharmProjects/flask-angular2-starter/src/client/node_modules/@angularclass/hmr-loader/index.js:10:21)
 @ multi main

ERROR in this is not a typed array.
